### PR TITLE
s/speed/duty/

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit f7ccd2c has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit f7ccd2c8c98e5a5aa2b5cf6b67d0aab463d35dff with merge b1837d45a1acc3ccb024f11a7f0d8b9a02771462...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/motor-driver/builds/335126445?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing b1837d45a1acc3ccb024f11a7f0d8b9a02771462 to master...

**Pull request merged**
