### PR TITLE
support TB6612FNG and L298

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 819a731 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 819a7319554d5a283423c65896e2e78339a7382e with merge 2f847d14f24a7b403411fa35c2f20166abca0189...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 34d627f has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 34d627faa8f336d303c37326986e30c2b9a93b63 with merge d46b7fed29e7a8f019a18c6f85126995c16bb614...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/motor-driver/builds/332951660?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing d46b7fed29e7a8f019a18c6f85126995c16bb614 to master...

**Pull request merged**
